package com.mtp.laboproject.listener

/**
 * Created on 2/2/18.
 */

interface RepositoryListener<T> {

    fun onFetchComplete(data: T)

    fun onFetchFail(failType: FailType)

    enum class FailType {

        NETWORK, INVALID_PROMO_CODE, ALREADY_CONSUMED, ORDER_NOT_FOUND, INVALID_SIGN_IN, USER_NOT_FOUND, EMPTY_GIFTS, EMPTY_WEEK_LIST, EMPTY_MONTH_LIST, BANNED_USER, INVALID_RESET_MDP, MAIL_UNIQUE, PASSWORD_MIN, OLD_PASSWORD, FACEBOOK_EXISTING, FACEBOOK_ID_TAKEN, SERVER, UNAUTHORIZED, INVALID_FACEBOOK_SIGN_IN, PASSWORD_CURRENTLY, INCORRECT_OLD_PASSWORD, FACEBOOK_CANCELED, FACEBOOK_ERROR,
        GRID_LIMIT, NOT_ENOUGH_CREDIT, GRID_TAKEN,
        NO_GRID_PLAYED, INCORRECT_FORMAT, LOTTERY_LOOT_ERROR, NO_PRODUCTS, NUMBER_ERROR, FORBIDDEN_ERROR, REFERENCE_ERROR,
        COMPLETE_ALL_PRODUCTS
    }

}
